name: Generate uuid test
on:
  workflow_dispatch:
  push:
permissions:
  contents: read
  pull-requests: write  

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set UUID
      id: generate-uuid
      uses: ./

    # use the output from the `generate-uuid` step
    - name: Get the UUID
      run: echo "UUID is ${{ steps.generate-uuid.outputs.uuid }}"
